// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ6hb21omNfDzX5GjFlRJ28N3WVEbUEP8',
    appId: '1:471622134386:web:84bddf28df6ab42ac7b0eb',
    messagingSenderId: '471622134386',
    projectId: 'wagwan-95fdf',
    authDomain: 'wagwan-95fdf.firebaseapp.com',
    storageBucket: 'wagwan-95fdf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRwYX1vuMyaCLJTGYRqL_UiBvCUenR_Rs',
    appId: '1:471622134386:android:47b842521893437ac7b0eb',
    messagingSenderId: '471622134386',
    projectId: 'wagwan-95fdf',
    storageBucket: 'wagwan-95fdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt4E-Psbrp0O0pBsvsNmkZxKPnKWQlHn0',
    appId: '1:471622134386:ios:d9925ae68796bc38c7b0eb',
    messagingSenderId: '471622134386',
    projectId: 'wagwan-95fdf',
    storageBucket: 'wagwan-95fdf.appspot.com',
    iosClientId: '471622134386-uhm46njnlg5jgq9mtkapj930h9pjr35l.apps.googleusercontent.com',
    iosBundleId: 'com.example.wagwan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt4E-Psbrp0O0pBsvsNmkZxKPnKWQlHn0',
    appId: '1:471622134386:ios:2703084d56efba66c7b0eb',
    messagingSenderId: '471622134386',
    projectId: 'wagwan-95fdf',
    storageBucket: 'wagwan-95fdf.appspot.com',
    iosClientId: '471622134386-k9qagtas9ub6k941v66kp1is694bcahb.apps.googleusercontent.com',
    iosBundleId: 'com.example.wagwan.RunnerTests',
  );
}
